import './globals.css'
import { Inter } from 'next/font/google'
import Menu from '../components/menu';
import Footer from '../components/footer';
import "bootstrap/dist/css/bootstrap.min.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Menu />
          <div>{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
